# Exported from Render on 2024-10-21T21:41:26Z
services:
- type: web
  name: Scheduling-Tool
  runtime: python
  repo: https://github.com/AIAssistantDeveloper/Scheduling-Tool
  services:
  - env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # Ensure `app` is the correct module where Flask instance is created
    envVars:
      - key: DATABASE_URL
        value: "postgresql://tony:whpu4CqOykeHuw2sdeQUrETBkHfCp24u@dpg-csdhupd6l47c73dbe57g-a/schedule_db_zdhr"
      - key: SQLALCHEMY_DATABASE_URL
        value: "DATABASE_URL"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_DEBUG
        value: "false"
  region: oregon
version: "1"
