# Exported from Render on 2024-10-20T03:14:05Z
services:
- type: web
  name: Scheduling-Tool
  runtime: python
  repo: https://github.com/AIAssistantDeveloper/Scheduling-Tool
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: FLASK_ENV
    sync: false
  - key: FLASK_DEBUG
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
version: "1"
